[package]
name = "csv_validator"
version = "0.1.0"
edition = "2021"
authors = ["Michael Nutt <michael@nuttnet.net>"]
license = "MIT"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
magnus = "0.7.1"
csv = "1.3.1"
url = "2.5.4"
